/**
 * Generated by scripts/location-maps.mjs — do not edit by hand.
 * Light editorial location maps (OpenStreetMap data, ODbL). Positions are in % of
 * the 4:3 frame; the property sits at the centre (50 %, 50 %).
 */
export type LocationMapData = {
  src: string;
  span: number;
  ring: { r: number; meters: number; label: { x: number; y: number } };
  scale: { meters: number; width: number };
  labels: { text: string; x: number; y: number; angle: number; frontage: boolean }[];
  stops: number;
};

export const locationMaps: Record<string, LocationMapData> = {
  "moscova-9": {
    "src": "/assets/maps/moscova-9.svg",
    "span": 800,
    "ring": {
      "r": 37.5,
      "meters": 300,
      "label": {
        "x": 77,
        "y": 14
      }
    },
    "scale": {
      "meters": 100,
      "width": 12.5
    },
    "labels": [
      {
        "text": "bd. Moscova",
        "x": 56,
        "y": 88,
        "angle": -75,
        "frontage": true
      },
      {
        "text": "str. Miron Costin",
        "x": 87.9,
        "y": 23.1,
        "angle": 15,
        "frontage": false
      }
    ],
    "stops": 2
  },
  "moscova-20": {
    "src": "/assets/maps/moscova-20.svg",
    "span": 800,
    "ring": {
      "r": 37.5,
      "meters": 300,
      "label": {
        "x": 77,
        "y": 14
      }
    },
    "scale": {
      "meters": 100,
      "width": 12.5
    },
    "labels": [
      {
        "text": "bd. Moscova",
        "x": 35.9,
        "y": 91.5,
        "angle": -75,
        "frontage": true
      },
      {
        "text": "str. Matei Basarab",
        "x": 64.1,
        "y": 89.9,
        "angle": 15,
        "frontage": false
      }
    ],
    "stops": 5
  },
  "dacia-31": {
    "src": "/assets/maps/dacia-31.svg",
    "span": 800,
    "ring": {
      "r": 37.5,
      "meters": 300,
      "label": {
        "x": 77,
        "y": 14
      }
    },
    "scale": {
      "meters": 100,
      "width": 12.5
    },
    "labels": [
      {
        "text": "bd. Dacia",
        "x": 8.7,
        "y": 9,
        "angle": 46,
        "frontage": true
      },
      {
        "text": "bd. Cuza-Vodă",
        "x": 92.5,
        "y": 68.1,
        "angle": -44,
        "frontage": false
      },
      {
        "text": "bd. Traian",
        "x": 5.8,
        "y": 65.2,
        "angle": -44,
        "frontage": false
      },
      {
        "text": "str. Praga",
        "x": 61.3,
        "y": 7.9,
        "angle": -79,
        "frontage": false
      }
    ],
    "stops": 7
  },
  "creanga-78": {
    "src": "/assets/maps/creanga-78.svg",
    "span": 800,
    "ring": {
      "r": 37.5,
      "meters": 300,
      "label": {
        "x": 77,
        "y": 14
      }
    },
    "scale": {
      "meters": 100,
      "width": 12.5
    },
    "labels": [
      {
        "text": "str. Ion Creangă",
        "x": 9.9,
        "y": 85.7,
        "angle": -28,
        "frontage": true
      },
      {
        "text": "str. Ion Pelivan",
        "x": 5.9,
        "y": 7.6,
        "angle": -54,
        "frontage": false
      },
      {
        "text": "str. Doina și Ion Aldea-Teodorovici",
        "x": 56.7,
        "y": 34.3,
        "angle": 62,
        "frontage": false
      },
      {
        "text": "str. Ioana Radu",
        "x": 56.9,
        "y": 82.2,
        "angle": -4,
        "frontage": false
      }
    ],
    "stops": 7
  },
  "drochia-gateway": {
    "src": "/assets/maps/drochia-gateway.svg",
    "span": 1600,
    "ring": {
      "r": 18.8,
      "meters": 300,
      "label": {
        "x": 63.5,
        "y": 32
      }
    },
    "scale": {
      "meters": 200,
      "width": 12.5
    },
    "labels": [
      {
        "text": "bd. Independenței",
        "x": 8.6,
        "y": 86.8,
        "angle": -31,
        "frontage": true
      },
      {
        "text": "str. Evgheni Gudanov",
        "x": 26.5,
        "y": 28.8,
        "angle": -2,
        "frontage": false
      },
      {
        "text": "str. Dorohoi",
        "x": 47,
        "y": 91.2,
        "angle": 50,
        "frontage": false
      },
      {
        "text": "str. Vasile Alecsandri",
        "x": 51.5,
        "y": 69.1,
        "angle": 51,
        "frontage": false
      }
    ],
    "stops": 0
  }
} as const;
